spring.application.name=flight-management

# ACTUALIZAR AUTOMATICAMENTE CUANDO GUARDEMOS LOS CAMBIOS
spring.thymeleaf.cache=false

# CAMBIAR EL PUERTO DEL SERVIDOR
server.port=8080

# QUITAR EL BANNER Y LOGO DE SPRING DEL LOG
spring.main.banner-mode=off

# PARAMETROS DE CONEXION A LA BD (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/flight_management
spring.datasource.username=postgres
spring.datasource.password=12345

# CONFIGURACION DE HIBERNATE / ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ESTO ES PARA PODER VER EN EL LOG EL SQL QUE SE HA GENERADO EN CADA OPERACION
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE









